import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/Kotlin/kotlinx.serialization
     */
    const val kotlinx_serialization_runtime: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" +
            Versions.org_jetbrains_kotlinx_kotlinx_serialization

    /**
     * https://github.com/Kotlin/kotlinx.serialization
     */
    const val kotlinx_serialization_runtime_common: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:" +
            Versions.org_jetbrains_kotlinx_kotlinx_serialization

    const val kotlinx_serialization_runtime_native: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:" +
            Versions.org_jetbrains_kotlinx_kotlinx_serialization

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core_common: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_test: String = "org.jetbrains.kotlinx:kotlinx-coroutines-test:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    const val kotlinx_coroutines_core_native: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    const val klock: String = "com.soywiz.korlibs.klock:klock:" + Versions.com_soywiz_korlibs_klock

    const val klock_jvm: String = "com.soywiz.korlibs.klock:klock-jvm:" +
            Versions.com_soywiz_korlibs_klock

    /**
     * https://github.com/square/sqldelight/
     */
    const val android_driver: String = "com.squareup.sqldelight:android-driver:" +
            Versions.com_squareup_sqldelight

    /**
     * https://github.com/square/sqldelight/
     */
    const val gradle_plugin: String = "com.squareup.sqldelight:gradle-plugin:" +
            Versions.com_squareup_sqldelight

    /**
     * https://github.com/square/sqldelight/
     */
    const val ios_driver: String = "com.squareup.sqldelight:ios-driver:" +
            Versions.com_squareup_sqldelight

    const val coroutines_extensions: String = "com.squareup.sqldelight:coroutines-extensions:" +
            Versions.com_squareup_sqldelight

    const val com_squareup_sqldelight_runtime: String = "com.squareup.sqldelight:runtime:" +
            Versions.com_squareup_sqldelight

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_serialization: String = "org.jetbrains.kotlin:kotlin-serialization:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_serialization_unshaded: String =
            "org.jetbrains.kotlin:kotlin-serialization-unshaded:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_common: String = "org.jetbrains.kotlin:kotlin-stdlib-common:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_annotations_common: String =
            "org.jetbrains.kotlin:kotlin-test-annotations-common:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_common: String = "org.jetbrains.kotlin:kotlin-test-common:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_junit: String = "org.jetbrains.kotlin:kotlin-test-junit:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    const val teaco: String = "com.egroden.teaco:teaco:" + Versions.com_egroden_teaco

    const val teaco_android: String = "com.egroden.teaco:teaco-android:" +
            Versions.com_egroden_teaco

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_core: String = "androidx.test:core:" + Versions.androidx_test

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test

    const val kodein_di_framework_android_x: String =
            "org.kodein.di:kodein-di-framework-android-x:" + Versions.org_kodein_di

    const val kodein_di_core: String = "org.kodein.di:kodein-di-core:" + Versions.org_kodein_di

    const val kodein_di_erased: String = "org.kodein.di:kodein-di-erased:" + Versions.org_kodein_di

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.io_mockk

    /**
     * http://mockk.io
     */
    const val mockk_common: String = "io.mockk:mockk-common:" + Versions.io_mockk

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_android: String = "io.ktor:ktor-client-android:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_core: String = "io.ktor:ktor-client-core:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_features: String = "io.ktor:ktor-client-features:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_ios: String = "io.ktor:ktor-client-ios:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_logging: String = "io.ktor:ktor-client-logging:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_logging_jvm: String = "io.ktor:ktor-client-logging-jvm:" +
            Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_serialization: String = "io.ktor:ktor-client-serialization:" +
            Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_serialization_jvm: String = "io.ktor:ktor-client-serialization-jvm:" +
            Versions.io_ktor

    const val ktor_client_logging_native: String = "io.ktor:ktor-client-logging-native:" +
            Versions.io_ktor

    const val ktor_client_serialization_native: String =
            "io.ktor:ktor-client-serialization-native:" + Versions.io_ktor

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    const val io_fabric_tools_gradle: String = "io.fabric.tools:gradle:" +
            Versions.io_fabric_tools_gradle

    const val de_fayard_refreshversions_gradle_plugin: String =
            "de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:" +
            Versions.de_fayard_refreshversions_gradle_plugin

    const val multiplatform_settings: String = "com.russhwolf:multiplatform-settings:" +
            Versions.multiplatform_settings

    const val app_killer_manager: String = "indrih17.app-killer-manager:app-killer-manager:" +
            Versions.app_killer_manager

    const val firebase_analytics: String = "com.google.firebase:firebase-analytics:" +
            Versions.firebase_analytics

    const val firebase_messaging: String = "com.google.firebase:firebase-messaging:" +
            Versions.firebase_messaging

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val swiperefreshlayout: String = "androidx.swiperefreshlayout:swiperefreshlayout:" +
            Versions.swiperefreshlayout

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.junit_jupiter_api

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val preference_ktx: String = "androidx.preference:preference-ktx:" +
            Versions.preference_ktx

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val exifinterface: String = "androidx.exifinterface:exifinterface:" +
            Versions.exifinterface

    const val firebase_core: String = "com.google.firebase:firebase-core:" + Versions.firebase_core

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

    const val crashlytics: String = "com.crashlytics.sdk.android:crashlytics:" +
            Versions.crashlytics

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * https://github.com/whalemare/sheetmenu
     */
    const val sheetmenu: String = "com.github.whalemare:sheetmenu:" + Versions.sheetmenu

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val cardview: String = "androidx.cardview:cardview:" + Versions.cardview

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://developer.android.com/testing
     */
    const val junit: String = "androidx.test.ext:junit:" + Versions.junit
}
