/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/Kotlin/kotlinx.serialization
     */
    const val kotlinx_serialization_runtime_common: String =
        "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:" +
                Versions.org_jetbrains_kotlinx_kotlinx_serialization

    const val kotlinx_serialization_runtime_native: String =
        "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:" +
                Versions.org_jetbrains_kotlinx_kotlinx_serialization

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_android: String =
        "org.jetbrains.kotlinx:kotlinx-coroutines-android:" +
                Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core_common: String =
        "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:" +
                Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    const val kotlinx_coroutines_core_native: String =
        "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:" +
                Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/square/sqldelight/
     */
    const val android_driver: String = "com.squareup.sqldelight:android-driver:" +
            Versions.com_squareup_sqldelight

    /**
     * https://github.com/square/sqldelight/
     */
    const val gradle_plugin: String = "com.squareup.sqldelight:gradle-plugin:" +
            Versions.com_squareup_sqldelight

    /**
     * https://github.com/square/sqldelight/
     */
    const val ios_driver: String = "com.squareup.sqldelight:ios-driver:" +
            Versions.com_squareup_sqldelight

    const val com_squareup_sqldelight_runtime: String = "com.squareup.sqldelight:runtime:" +
            Versions.com_squareup_sqldelight

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
        "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
        "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
                Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
        "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
                Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_serialization: String = "org.jetbrains.kotlin:kotlin-serialization:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_serialization_unshaded: String =
        "org.jetbrains.kotlin:kotlin-serialization-unshaded:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_common: String = "org.jetbrains.kotlin:kotlin-stdlib-common:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_annotations_common: String =
        "org.jetbrains.kotlin:kotlin-test-annotations-common:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_common: String = "org.jetbrains.kotlin:kotlin-test-common:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_junit: String = "org.jetbrains.kotlin:kotlin-test-junit:" +
            Versions.org_jetbrains_kotlin

    const val teaco: String = "com.egroden.teaco:teaco:" + Versions.com_egroden_teaco

    const val teaco_android: String = "com.egroden.teaco:teaco-android:" +
            Versions.com_egroden_teaco

    const val kodein_di_framework_android_x: String =
        "org.kodein.di:kodein-di-framework-android-x:" + Versions.org_kodein_di

    const val kodein_di_core: String = "org.kodein.di:kodein-di-core:" + Versions.org_kodein_di

    const val kodein_di_erased: String = "org.kodein.di:kodein-di-erased:" + Versions.org_kodein_di

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_android: String = "io.ktor:ktor-client-android:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_core: String = "io.ktor:ktor-client-core:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_features: String = "io.ktor:ktor-client-features:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_ios: String = "io.ktor:ktor-client-ios:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_logging: String = "io.ktor:ktor-client-logging:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_logging_jvm: String = "io.ktor:ktor-client-logging-jvm:" +
            Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_serialization: String = "io.ktor:ktor-client-serialization:" +
            Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_serialization_jvm: String = "io.ktor:ktor-client-serialization-jvm:" +
            Versions.io_ktor

    const val ktor_client_logging_native: String = "io.ktor:ktor-client-logging-native:" +
            Versions.io_ktor

    const val ktor_client_serialization_native: String =
        "io.ktor:ktor-client-serialization-native:" + Versions.io_ktor

    /**
     * https://developer.android.com/testing
     */
    const val com_android_support_test_runner: String = "com.android.support.test:runner:" +
            Versions.com_android_support_test_runner

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    const val de_fayard_refreshversions_gradle_plugin: String =
        "de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:" +
                Versions.de_fayard_refreshversions_gradle_plugin

    const val multiplatform_settings: String = "com.russhwolf:multiplatform-settings:" +
            Versions.multiplatform_settings

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "com.android.support.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * http://mockk.io
     */
    const val mockk_common: String = "io.mockk:mockk-common:" + Versions.mockk_common

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    const val klock: String = "com.soywiz.korlibs.klock:klock:" + Versions.klock
}
