/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_serialization: String = "0.13.0"

    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.2"

    const val com_soywiz_korlibs_klock: String = "1.7.4"

    const val com_squareup_sqldelight: String = "1.2.0"

    const val org_jetbrains_kotlin: String = "1.3.60"

    const val androidx_navigation: String = "2.1.0"

    const val com_egroden_teaco: String = "0.2.2"

    const val androidx_test: String = "1.2.0"

    const val org_kodein_di: String = "6.4.1"

    const val io_mockk: String = "1.9.3"

    const val io_ktor: String = "1.3.0-beta-1"

    const val com_android_tools_build_gradle: String = "3.5.2"

    const val io_fabric_tools_gradle: String = "1.31.2"

    const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0" // available: "0.8.3"

    const val multiplatform_settings: String = "0.3.3"

    const val app_killer_manager: String = "0.3.6"

    const val firebase_analytics: String = "17.2.1"

    const val firebase_messaging: String = "20.0.1"

    const val swiperefreshlayout: String = "1.0.0"

    const val junit_jupiter_api: String = "5.5.2"

    const val constraintlayout: String = "2.0.0-beta2"

    const val google_services: String = "4.3.3"

    const val preference_ktx: String = "1.1.0"

    const val espresso_core: String = "3.2.0"

    const val exifinterface: String = "1.0.0"

    const val firebase_core: String = "17.2.1"

    const val fragment_ktx: String = "1.2.0-beta02"

    const val recyclerview: String = "1.0.0"

    const val crashlytics: String = "2.10.1"

    const val lint_gradle: String = "26.5.2"

    const val appcompat: String = "1.1.0"

    const val sheetmenu: String = "2.0.1"

    const val cardview: String = "1.0.0"

    const val core_ktx: String = "1.1.0"

    const val material: String = "1.1.0-beta01"

    const val aapt2: String = "3.5.2-5435860"

    const val junit: String = "1.1.1"

    /**
     * Current version: "5.6.4"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0"
}
