/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_serialization: String = "0.13.0"

    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.2"

    const val com_squareup_sqldelight: String = "1.2.0"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val com_egroden_teaco: String = "0.1.0"

    const val org_kodein_di: String = "6.4.1"

    const val io_ktor: String = "1.3.0-beta-1"

    const val com_android_support_test_runner: String = "1.0.2"

    const val com_android_tools_build_gradle: String = "3.5.1"

    const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0"

    const val multiplatform_settings: String = "0.3.3"

    const val espresso_core: String = "3.0.2"

    const val mockk_common: String = "1.9.3"

    const val lint_gradle: String = "26.5.1"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.1.0"

    const val aapt2: String = "3.5.1-5435860"

    const val junit: String = "4.12"

    const val klock: String = "1.7.4"

    /**
     * Current version: "5.6.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"
}
